# Generated by Django 3.2.15 on 2022-10-07 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('members', '0002_auto_20220922_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('account', 'email')},
        ),
    ]
