# Generated by Django 3.2.15 on 2022-12-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20221209_1741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='user_name',
            new_name='name',
        ),
    ]
