# Generated by Django 3.2.15 on 2022-12-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_owner_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='membership',
            field=models.BooleanField(default=False),
        ),
    ]
