# Generated by Django 3.2.15 on 2022-09-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='member',
            name='owner_textfield',
        ),
    ]
