# Generated by Django 3.2.15 on 2022-12-15 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.CharField(default='Beginner', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='title',
            field=models.CharField(default='-', max_length=8),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last_login'),
        ),
    ]
