# Generated by Django 3.2.15 on 2022-12-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221215_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(default='empty', max_length=200, null=True, unique=True, verbose_name='email address'),
        ),
    ]
