# Generated by Django 3.2.15 on 2022-09-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_and_classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='EventsAndClasses',
        ),
    ]
