# Generated by Django 3.2.15 on 2022-09-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.CharField(max_length=200)),
                ('member', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
