# Generated by Django 3.2.15 on 2022-10-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='owner_textfield',
        ),
    ]
