# Generated by Django 3.2.15 on 2022-10-05 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20221004_1513'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created']},
        ),
    ]
