# Generated by Django 3.2.15 on 2022-12-14 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20221007_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='member',
        ),
        # migrations.AddField(
        #     model_name='booking',
        #     name='members',
        #     field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
        # ),
    ]
