# Generated by Django 3.2.15 on 2022-12-14 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20221214_1249'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='booking',
    #         name='members',
    #         field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='members.member'),
    #     ),
    
    # ]
