# Generated by Django 3.2.15 on 2022-12-15 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_membership_account_member'),
        ('bookings', '0008_alter_booking_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
