# Generated by Django 3.2.15 on 2022-12-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booking_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='account',
        ),
    ]
