# Generated by Django 3.2.15 on 2023-03-01 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_user'),
        ('bookings', '0011_booking_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='account',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
