# Generated by Django 3.2.15 on 2022-08-17 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_length', models.IntegerField()),
                ('next_event', models.DateTimeField()),
                ('frequency', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=8)),
                ('first_name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('last_login', models.DateTimeField(verbose_name='Last login')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='bookings.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.member', unique=True)),
            ],
        ),
    ]
